### PR TITLE
Bump alpine and GHC

### PR DESCRIPTION
**Pull request by BardurArantsson**
Bumps:

* alpine 3.16.1 -> 3.16.3
* ghc 9.2.4 -> 9.2.5

(I notice that there is an alpine 3.17.0 out now, but perhaps a bit early to update to that?)

### CODE REVIEW

**Review by aycanirican — APPROVED** [review]
Looks good, thank you.

**Comment by TravisCardwell** [comment]
Thanks!

I think that using the latest Alpine release is fine.  I will bump the Alpine version as well as add GHC 9.4.3.

@utdemir Could you then make a release?

* [ ] Bump `GHC_MUSL_VERSION`
* [ ] Update the README
* [ ] Push to Docker Hub

**Comment by utdemir** [comment]
> @utdemir Could you then make a release?
> 
> * [ ]  Bump `GHC_MUSL_VERSION`
> * [ ]  Update the README
> * [ ]  Push to Docker Hub

Thank you @TravisCardwell, I will. I’m on my vacation and will only have reliable internet access in a couple of days, so expect a release in a week or so :)

**Comment by BardurArantsson** [comment]
Ping @utdemir :smile: 

Btw, there might be further bumps, I think there's been a new stack release and a GHC release.

**Comment by TravisCardwell** [comment]
I updated the `Earthfile` to use GHC 9.4.4.

As for Stack, it always installs the latest version, so no changes to our configuration are required.  Once merged, it should install the latest version whenever an image is built.

**Comment by utdemir** [comment]
Thanks for the ping @BardurArantsson .

I was trying to cut a release and had a couple of issues. Currently the builds fail on my machine without a useful error message.

```
$ earthly --allow-privileged +ghc944 --platform linux/amd64
...
                +ghc *failed* | # We finally replace the original file.
                +ghc *failed* | mv '/usr/local/.ghcup/tmp/ghcup-2dd427b1d7c827c0/usr/local/.ghcup/ghc/9.4.4/lib/ghc-9.4.4/lib/package.conf.d/ghc-bignum-1.3.conf.copy.copy' '/usr/local/.ghcup/tmp/ghcup-2dd427b1d7c827c0/usr/local/.ghcup/ghc/9.4.4/lib/ghc-9.4.4/lib/package.conf.d/ghc-bignum-1.3.conf'
                +ghc *failed* | # Fix the mode, in case umask is set
                +ghc *failed* | chmod 644 '/usr/local/.ghcup/tmp/ghcup-2dd427b1d7c827c0/usr/local/.ghcup/ghc/9.4.4/lib/ghc-9.4.4/lib/package.conf.d/ghc-bignum-1.3.conf'
                +ghc *failed* | '/usr/local/.ghcup/tmp/ghcup-2dd427b1d7c827c0/usr/local/.ghcup/ghc/9.4.4/lib/ghc-9.4.4/bin/ghc-pkg' --global-package-db "/usr/local/.ghcup/tmp/ghcup-2dd427b1d7c827c0/usr/local/.ghcup/ghc/9.4.4/lib/ghc-9.4.4/lib/package.conf.d" recache
                +ghc *failed* | ERROR Earthfile line 49:2
                +ghc *failed* |       The command
                +ghc *failed* |           RUN ghcup --verbose install ghc "$GHC" --set
                +ghc *failed* |       did not complete successfully. Exit code 255
Share your logs with an Earthly account (experimental)! Register for one at https://ci.earthly.dev.
Error: build target: build main: failed to solve: process "/bin/sh -c ALPINE_VERSION=3.17.0 BASE_TAG=utdemir/ghc-musl:v24- EARTHLY_LOCALLY=false GHC=9.4.4 GHCUP_INSTALL_BASE_PREFIX=/usr/local GHC_MUSL_VERSION=24 PATH=/usr/local/.ghcup/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /usr/bin/earth_debugger /bin/sh -c 'ghcup --verbose install ghc \"$GHC\" --set'" did not complete successfully: exit code: 255
```

Similar results on other GHC versions too. I recently moved to an M1-powered Mac which is likely the issue. @TravisCardwell are you able to build it on your machine?

If it ends up being a problem on my machine, I will try to spin up a Linux VPS.

**Comment by TravisCardwell** [comment]
@utdemir I tested before pushing the change, and it builds on my machine without issues.

```
$ docker images | head -n 2
REPOSITORY                       TAG                              IMAGE ID       CREATED         SIZE
utdemir/ghc-musl                 v24-ghc944                       b419cc2bd095   3 hours ago     3.92GB
```

**Comment by BardurArantsson** [comment]
FWIW, it also builds fine on my Arch Linux machine.

**Comment by utdemir** [comment]
Thanks @TravisCardwell and @BardurArantsson ,

I think it is an issue with M1 Mac's for some reason. I spun up a VM on DigitalOcean, and there I was able to push `v25` which includes the recent changes.

I'll try to be more timely with updates.

**Pull request merged**
