### PR TITLE
ghc: 9.2.1 -> 9.2.2

### PR DESCRIPTION
**Pull request by TravisCardwell**

### CODE REVIEW

**Comment by utdemir** [comment]
Awesome, thanks @TravisCardwell!

I just tried it locally and tests pass, thanks to your previous PR #20 . I'll merge it and cut a new release.

**Comment by TravisCardwell** [comment]
Thank you!  I just pulled the new images and confirmed that everything builds without issue.

It is more than the [three release policy](https://gitlab.haskell.org/haskell/prime/-/wikis/libraries/3-release-policy), but would you be open to adding support for GHC 8.8.4 as well?  I built an image locally, but my project cannot support it unless it is on Docker Hub and available to anybody.  I am happy to submit a PR.

**Comment by utdemir** [comment]
> but would you be open to adding support for GHC 8.8.4 as well? ... I am happy to submit a PR.

Yes, definitely! I have no issues with supporting more than three releases, if they are available on `ghcup` and so do not complicate the build process too much. I'd be more than happy to merge your PR.

> my project

If you have an active project utilizing `ghc-musl`, I'd be happy to add you as a co-maintainer too. Let me know if you prefer that :)

**Comment by TravisCardwell** [comment]
Thank you!  I have submitted a new PR that adds GHC 8.8.4 support.

I am currently migrating the [lsupg][] project to use `ghc-musl`.   This utility lists items in a container that can be upgraded.  It works by mounting the executable and executing it within an arbitrary container, so the executable must be fully static.  For example, the following shows which Alpine packages in `utdemir/ghc-musl:v24-ghc922` have updates available.

[lsupg]: <https://github.com/ExtremaIS/lsupg-haskell#lsupg>

```
$ lsupg --docker utdemir/ghc-musl:v24-ghc922
apk  busybox                 1.34.1-r3    1.34.1-r4
apk  ca-certificates-bundle  20191127-r7  20211220-r0
apk  libcrypto1.1            1.1.1l-r8    1.1.1n-r0
apk  libssl1.1               1.1.1l-r8    1.1.1n-r0
apk  libretls                3.3.4-r2     3.3.4-r3
apk  ssl_client              1.34.1-r3    1.34.1-r4
apk  bash                    5.1.8-r0     5.1.16-r0
apk  expat                   2.4.4-r0     2.4.7-r0
apk  openssl-dev             1.1.1l-r8    1.1.1n-r0
apk  openssl-libs-static     1.1.1l-r8    1.1.1n-r0
apk  libxml2                 2.9.12-r2    2.9.13-r0
```

I am surprised to see so many updates for an image that was built so recently.  I assume that `ghc-musl` containers are not public-facing, but statically linking old versions of libraries could have security implications for the static executables built using `ghc-musl`.  I will look into it.

I am happy to help maintain the project.  I just want to be careful that I do not step on any toes. :bow:  I wrote my own version of the `Earthfile` while testing, mostly to learn Earthly, and I have a number of suggestions for changes.  I will organize these in an issue to see what you think about them.

**Pull request merged**
