### PR TITLE
Add related

### PR DESCRIPTION
**Pull request by benz0li**
- https://github.com/benz0li/ghc-musl

### CODE REVIEW

**Comment by benz0li** [comment]
Maintained and up-to-date docker images for `linux/amd64` and `linux/arm64/v8`.

Built using Hadrian, from [official releases of GHC source code](https://downloads.haskell.org/~ghc), without docs. 

👉 Used to build the Linux amd64 and arm64 binary [releases of pandoc](https://github.com/jgm/pandoc/releases).
(I have just migrated the project from [ghc/ghc4pandoc](https://gitlab.b-data.ch/ghc/ghc4pandoc) to [ghc/ghc-musl](https://gitlab.b-data.ch/ghc/ghc-musl))

Ping @utdemir, @TravisCardwell

**Comment by TravisCardwell** [comment]
Thank you, @benz0li !  Your project looks really nice, and I look forward to trying it out.

**Comment by utdemir** [comment]
I do agree, your project looks great, thanks! 

I think you made a good choice not trying to deduplicate the Dockerfile's, I found it painful here, even though we're relying on `ghcup` to do all the hard work.

To be honest, I did not have much incentive to develop this, so @TravisCardwell was doing all the work here. @benz0li , I'd be more than happy to deprecate this (if @TravisCardwell agrees) and point everyone to your project. I guess the problem with these projects is that they are a constant maintenance burden, and tend to get less and less maintained over time (incl. ours and everyone before us) unless there's an org backing. So I hope yours will fare better.

What do you think @benz0li & @TravisCardwell ? Should we combine efforts on the new repository, or should we continue them separately?

**Comment by benz0li** [comment]
> To be honest, I did not have much incentive to develop this, so @TravisCardwell was doing all the work here.

My incentive was to resolve https://github.com/jgm/pandoc/issues/5450. That is why I initially called it `ghc/ghc4pandoc`.

> @benz0li , I'd be more than happy to deprecate this (if @TravisCardwell agrees) and point everyone to your project.

You may point everyone to my project. But there should be a transition time before you abandon yours.

> I guess the problem with these projects is that they are a constant maintenance burden,

Yes, indeed.

> and tend to get less and less maintained over time (incl. ours and everyone before us) unless there's an org backing. So I hope yours will fare better.

Since I depend on pandoc's arm64 binary release, I intend to continue updating [ghc/ghc-musl](https://gitlab.b-data.ch/ghc/ghc-musl).

> What do you think @benz0li & @TravisCardwell ? Should we combine efforts on the new repository, or should we continue them separately?

I am happy maintaining `ghc/ghc-musl` on my own. What you want to do with `utdemir/ghc-musl` is up to you.

**Comment by TravisCardwell** [comment]
Combining efforts sounds good to me, and I agree that we should provide users a transition period.

**Comment by TravisCardwell** [comment]
@utdemir
I just merged two changes to `main`, for GHC `9.2.7` and `9.6.1`.  Would you like to update the README to add a message recommending the new project before making a release?

By the way, it looks like Docker Hub is going to delete open-source organizations in about a month!  ([HN discussion](https://news.ycombinator.com/item?id=35166317))  I do not know the details, but perhaps this project's images will be removed then?  If so, then this transition has pretty good timing.

**Comment by benz0li** [comment]
> By the way, it looks like Docker Hub is going to delete open-source organizations in about a month!

This burdens many open-source projects with either unplanned costs or additional work.

I have chosen to put my/[b-data](https://github.com/b-data)'s docker images in a self-hosted [GitLab Container Registry](https://gitlab.b-data.ch/help/user/packages/container_registry/index).

**Pull request merged**
